server:
  port: 80

# sms相关配置
aliyun:
  sms:
    regionId: default
    systemDomain: dysmsapi.aliyuncs.com
    systemVersion: 2017-05-25
    accessKeyId: xxxxxxxxxxx
    secret: xxxxxxxxxxx
    signName: gkiiot

# redis相关配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms
