server:
  port: 80

spring:
  application:
    name: mybatis-plus-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.18.139:3306/my_test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: fdauto

mybatis-plus:
  type-aliases-package: com.cn.demo
  global-config:
    banner: false
    db-config:
      id-type: AUTO
      insertStrategy: NOT_EMPTY
      updateStrategy: NOT_EMPTY
      selectStrategy: NOT_EMPTY
      table-underline: true
      logic-delete-value: 2
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  typeEnumsPackage: com.hciot.common.core.enums
